### ISSUE TITLE
wrong icon_size on a any item the mod touches

### ISSUE THREAD

**Issue by miezebieze** [ndisalvio3/FacTrain_Reborn#1]
all items you modified look weird and hard/not at all to distinguish because you set too small icon_size.

i grep'd Factorio's data and the only prototypes with icon_size = 32 are some graphical effects.
a few other things have icon_size 128 and 256 but recipe and item icons are all 64.

changing all `icon_size = 32` to `icon_size = 64` fixes the problem.

i won't create a pr because i never did that and have no time to learn howto.

**Comment by ndisalvio3** [comment]
Fixed with latest release.
